### ISSUE TITLE
Add a "Notes" section

### ISSUE THREAD

**Issue by sedulam** [daviseford/aos-reminders#1000]
When designing a list, we usually have a strategy in mind, that we sometimes deviate during the game in the heat of the moment. This strategy is not something we want to reveal to the opponent. Although it's an unspoken rule that we should answer all unit questions, giving away the overall strategy, is not something that should be answered (obviously IMO).
Although the Warscroll Builder has a section for notes, the downloaded PDF is something that it's usually shared with the opponent for list points validation.

So my suggestion for AoS Reminders is to have a "Notes" section where we could put this strategy to remember during the game. It could be at the top or the bottom, but even better yet, each object in the AoS Reminders could have a "Notes" section beside it. For instance:
I'm taking a Bound Malevolent Maelstrom and I have a Skink Starpriest with the "Bind Endless Spell" spell from its lore, but I would like a reminder in the "Summon Bound Maelstrom" object reminding me that I should only cast the Maelstrom if the enemy doesn't have Endless Spell in the table for me to use "Bind Endless Spell" on.

**Comment by daviseford** [comment]
Very good idea. I like this idea a lot.
