### ISSUE TITLE
Email Verification & Subscription

### ISSUE THREAD

**Issue by mikehoebee** [daviseford/aos-reminders#1008]
Hi

I am having trouble verifying my email and with subscription.  The link you sent me does not work 

![image](https://user-images.githubusercontent.com/71409928/93392035-04db7580-f868-11ea-8dba-2301cad3319f.png)
- please see attached image.

I have also not seen any changes to my subscription when logged on - presumably because I'm not verified - and have ended up paying twice.  Please could you help!!!

**Comment by daviseford** [comment]
Looking into this.

**Comment by daviseford** [comment]
Mike, thanks for the email. I am really sorry you're having difficulties.

1. I have refunded your second payment :)

2. I have verified that you are subscribed to AoS Reminders and your subscription is accurately reflected in both Stripe and AoS Reminders databases.

3. I have re-sent a verification email to your email address

Please try to login again to AoS Reminders and see if it works for you now :)

4. If you cannot manage to get verified, I can always change your user account to a dummy password and let you log in and change it :)

**Please let me know if things aren't working for you. I will get back to you ASAP.**

P.S. by way of apology, I've added six gift subs (for 1 year each) to your account. Feel free to give them to friends or create another account :D

**Comment by daviseford** [comment]
I think when the double-subscription happened, it borked some code that looks up your username. It probably wasn't written to handle two usernames with the same email like that :) I'll look into it.

**Comment by daviseford** [comment]
Solved :)
