### ISSUE TITLE
Unable to import list

### ISSUE THREAD

**Issue by xchagger** [daviseford/aos-reminders#1026]
Importing the attached list results in the the attached screenshot. The loading icon just keeps spinning indefinitely.

List: 
[List - Bad Moon Cafe Superleague Sept 2020.pdf](https://github.com/daviseford/aos-reminders/files/5274247/List.-.Bad.Moon.Cafe.Superleague.Sept.2020.pdf)

Result: 
![image](https://user-images.githubusercontent.com/7968714/94115286-6c358e80-fe41-11ea-9e88-0cf364eb64d2.png)

Occurs on multiple browsers:
Opera Version 70.0.3728.189
Chrome Version 85.0.4183.121 (Official Build) (64-bit)

Any tips / advice on my list welcome! :)

**Comment by exonian** [comment]
Thanks for the excellent report.
I can replicate this. In fact, I can't get *any* list to import right now 😬

**Comment by exonian** [comment]
Cannot replicate locally, both running v3.1.6

**Comment by daviseford** [comment]
```
azyrPdf.ts:72 TypeError: Cannot read property 'GlobalWorkerOptions' of undefined
    at azyrPdf.ts:16
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at a (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
    at azyrPdf.ts:14
(anonymous) @ azyrPdf.ts:72
parseFile.ts:70 Uncaught (in promise) TypeError: Cannot read property 'startsWith' of undefined
    at parseFile.ts:70
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at a (asyncToGenerator.js:25)
```

**Comment by daviseford** [comment]
My assumption right now is that there is a CDN issue and pdf-js is not getting delivered... let's see

**Comment by daviseford** [comment]
The build to production is taking a long time...

**Comment by daviseford** [comment]
FIXED! Thank you for opening this issue! @xchagger 

Please visit aosreminders.com to get the update. I appreciate you raising this issue SO MUCH!

**Comment by xchagger** [comment]
Confirmed, it is working now. Thanks for the quick turnaround!
