### ISSUE TITLE
Importing Saurus Scar-veteran on Cold One, parsed as Carnosaur

### ISSUE THREAD

**Issue by sedulam** [daviseford/aos-reminders#1037]
If I import [this list](https://drive.google.com/file/d/1ElatR9-3UnlOo5Q_3EzBlWqBKt9X25w7/view?usp=sharing), the Scar-veteran is parsed as being on Carnosaur, although in the list, it's riding a Cold one.

**Comment by exonian** [comment]
Great report.

So, I think I know what's going on here. Whichever version you add, it lists it only with its warscroll name, and not its subtitle. So we can't actually tell which one it is, because either one would show up the same in the Azyr export (we're not parsing either points or pictures 😅)

The only way around this at the moment is to include it in the [`AzyrAmbiguousNamesMap`](https://github.com/daviseford/aos-reminders/blob/2b9c7be21cc8cd03a3543703101beaa22dd776c5/src/utils/import/options.ts#L414-L444) so the user gets a warning when importing either from Azyr, so that they might be able to spot and fix it themselves.

Not sure when I'll get to this, so if anyone else wants to, that's the fix.

**Comment by sedulam** [comment]
Hadn't noticed that the mount didn't even show up on the PDF. Good catch! The Azyr app is sooo full of things that are either buggy or badly done, that it's surprising how a high-revenue company like GW didn't come up with something better... Oh well... /shrug
Don't worry about this one. It's a quick fix after importing the list. Just added it in here so you're aware. ;)

**Comment by exonian** [comment]
Cool, glad the solution makes sense to you. We'll get the warning in there, as you say it's then a quick fix for the user, but without the warning it's really hard to notice it's even done it. Fortunately it's a one-liner, I just need to remember the confusing way around to write it.

And yeah, it's pretty wild some of the stuff aosr has to put up with from Azyr 😅

**Comment by sedulam** [comment]
I would argue that it might make sense to drop the support for Azyr... I would guess that most of AOSR users, don't mind redoing a finalized list on Warscroll Builder (I wouldn't at least). Azyr is good to do lists on-the-go. But after a list is completed, it should be quick to just copy it to Warscroll Builder.
This would free your time up to focus on more important stuff related to Warscroll Builder imports, which is, I guess, the main source of your imports, as well as other improvements. (I would love to help with code contributions, but JavaScript and Scala are my nemeses. I'm more of a Java and Apache Cassandra guy. :) )
@daviseford , just out of curiosity, do you know the ratio of format imports (Azyr vs Warscroll Builder)?

**Comment by daviseford** [comment]
Warscroll Builder accounts for most of the imports.

![Capture](https://user-images.githubusercontent.com/9663863/96571412-88d6b200-1299-11eb-9d74-d6b6ef30aa13.PNG)

That's data from the last 30 days.

I won't drop Azyr support unless it goes lower. Now Battlescribe on the other hand... that's becoming a real chore to maintain.

**Comment by daviseford** [comment]
There _is_ a decent correlation between people who use the Import features, and people who subscribe. So I definitely don't want to take any import functionality away :)

**Comment by sedulam** [comment]
Holy guacamole! I was pleasantly surprised by this today. If half the apps in the world had this kind of fixes and improvements, people would be blissful (ok, maybe that's a stretch... :))!
Kudos for all your work guys. You ROCK!
![image](https://user-images.githubusercontent.com/9039639/97058532-ffb7c780-1585-11eb-8b1d-3440ddd65e59.png)
