### ISSUE TITLE
[FEATURE] New data structure for armies

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#1073]
**Is your feature request related to a problem? Please describe.**
New army books don't match up to AoS Reminders very well right now. We are having to hack around with allegiances too much. We should introduce a new layer of data.

>  the new SCE selection is causing the problem, though I think seraphon are structured this way too - @JohnSchramm 

**Describe the solution you'd like**
Discuss in this thread. I will post some useful stuff below.

**Describe alternatives you've considered**
n/a, we really need to move to this model

**Additional context**

```
So like two different selection paths for SCE would look like this:
SCE -> Legends of the Living Tempest (Default Allegiance ability name) -> Hammers of Sigmar (Stormhost subfaction)
SCE -> Stormkeep -> Hammers of Sigmar
You get all the command traits, mounts, artefacts, standars, lights, etc...  We just have the stuff in the allegiances that aren't technically allegiances.
``` 
from @JohnSchramm  

---

![matrix](https://user-images.githubusercontent.com/9663863/100408299-a802f500-3038-11eb-821d-4e6225f02f30.png)

from @JohnSchramm  (amazing work man)

---

> My biggest problem was that abilities.ts didn't have a mechanism for multiple entries - @JohnSchramm 

---

@JohnSchramm 
> I would like to make an appeal for making the lower level data containers match the book breakdown.  It would be a pretty safe assumption since all of the books in the last few years follow the same conventions.  Could fit into a modular approach.

**Davis says: Absolutely agreed**

@thundergore 
> without the requirement to validate a list, modular is easier no

@JohnSchramm 
> If we're going through and changing stuff like that anyway, I mean

@exonian 
> So like if you try to mix everything up to start with you end up with stormhosts multiplied by allegiance variants, but I think you could have it where you could more dynamically bring in, say, the valid battalions
> Essentially that you don't have, in psuedocode, get_battalions(stormcast) you have get_battalions(stormcast, subfaction, some other info)
> Yep making the data structure match the books should definitely be a priority imo
> And then the interface can kinda match the books too, but in a quite different way
> Like with what we were saying earlier about the "Army" dropdown mapping properly to the books, but then having all the collected stuff from the other books in there

@JohnSchramm 
> Yeah you would just label the battalions with their supported allegiance or w/e identifier so the get_battalions() works more intelligently?

@exonian 
> Yeah I think so

@JohnSchramm 
> Could work.  I have to label half the stuff I enter anyway, what's a few more things lol

**Comment by daviseford** [comment]
> I think Seraphon/SCE are a good candidate- but are LoN/all of those sub-legions also a good candidate?
> I guess also Orruks -> Bonesplittz/Ironjawz is another awkward one

**Comment by daviseford** [comment]
- [Top Tier: Factions, Sub-Factions, and Allegiances](#top-tier-factions-sub-factions-and-allegiances)
  - [Glossary](#glossary)
    - [Faction](#faction)
    - [Sub-Factions](#sub-factions)
      - [Base Sub-Faction](#base-sub-faction)
    - [Allegiances](#allegiances)
  - [Examples](#examples)

# Top Tier: Factions, Sub-Factions, and Allegiances


## Glossary

### Faction

First, let's define a **Faction**

- A **Faction** is the highest-level representation of a army/faction in AoS.
- A **Faction** is the aggregate set of rules that govern many **Sub-Factions**. 
- If a **Faction** only has one **Sub-Faction**, that will be considered the **Base Sub-Faction**
 - A **Faction** must have a **Base Sub-Faction** 
- If a **Faction** has multiple **Sub Factions**, 
  - It must assign one as a **Base Sub-Faction**
 - And the user will be allowed to select a variant

### Sub-Factions

Next, **Sub-Factions**.

- A Sub-Faction belongs to a **Faction**
- A **Sub-Faction** can dictate:
  - What **Allegiances** it may contain
  - What units it has
  - What battalions it has
- A **Sub-Faction** may also apply certain Abilities or effects, units, spells, etc

#### Base Sub-Faction

A **Sub-Faction** may be a **Base Sub-Faction**

A **Base Sub-Faction** can mark itself as **Not Visible**

We generally will try to extend other **Sub-Factions** from the **Base Sub-Faction**

  - For example - `Ironjawz` and `Bonesplitterz` (**Sub-Factions**) share a lot of data from the `Orruk Warclans` (**Faction**) book. 
  - So we would want three **Sub-Factions** in total:
    - **Base Sub-Faction** - marked as **Not Visible**
    - **`Ironjawz` Sub-Faction**
    - **`Bonesplitterz` Sub-Faction**

### Allegiances

Lastly in this high-level tier (but at the bottom), **Allegiances**

- These are the more "traditional" ways of configuring **Factions**. 
- An **Allegiance** may belong to a one or many **Sub-Factions**
- An **Allegiance** can dictate:
- What units/battalions it has
- An **Allegiance** can also apply Abilities or effects units, spells, etc

- TBD: Can **Allegiances** be shared across **Factions**?

## Examples

The new Seraphon book is a good example.


---
> If your army is a COALESCED army, you can give it the KOATL'S CLAW or THUNDER LIZARD keyword.

```
  COALESCED_ALLEGIANCES: [KOATLS_CLAW, THUNDER_LIZARD],
  STARBORNE_ALLEGIANCES: [DRACOTHIONS_TAIL, FANGS_OF_SOTEK],
```

---

|              |                                                                 |                                                                        |
| ------------ | --------------------------------------------------------------- | ---------------------------------------------------------------------- |
| Faction      | 'SERAPHON'                                                      | -                                                                      |
| Sub-Factions | 'COALESCED' or 'STARBORNE'                                      | one of these would be the **Base Sub-Faction**                         |
| Allegiances  | 'KOATLS_CLAW, THUNDER_LIZARD, DRACOTHIONS_TAIL, FANGS_OF_SOTEK' | the **Sub-Factions** will list which **Allegiances** they want to list |


|              |                                                                 |                                                                        |
| ------------ | --------------------------------------------------------------- | ---------------------------------------------------------------------- |
| Faction      | 'SERAPHON'                                                      | asd                                                                    |
| Sub-Factions | 'COALESCED' or 'STARBORNE'                                      | one would be **Base Sub-Faction**                                      |
| Allegiances  | 'KOATLS_CLAW, THUNDER_LIZARD, DRACOTHIONS_TAIL, FANGS_OF_SOTEK' | the **Sub-Factions** will list which **Allegiances** they want to list |

**Comment by thundergore** [comment]
> TBD: Can Allegiances be shared across Factions?

GW have precedent for making this the case in some of their systems (like for example, Ynnari in 40k). In the Ynnari example, I _think_ most stuff (traits and artefacts etc) is unique to "Ynarri" even if their units are from the entire Eldar range (multiple factions).

And my thought then is - to what extent would it make sense to future proof the project against all the potential variations of slightly mad list construction GW might implement?

**Comment by exonian** [comment]
Flava

**Comment by daviseford** [comment]
`/src/armies/` -> `/src/factions/`

**Comment by daviseford** [comment]
![sdfds](https://user-images.githubusercontent.com/9663863/100475236-a37a2300-30b0-11eb-97ba-b9b6172ab39e.png)

**Comment by daviseford** [comment]
```ts
const factionName = 'SERAPHON'

const subfactionNames = {
  COALESCED: 'COALESCED',
  STARBORNE: 'STARBORNE',
}

const coalescedSubfaction = {
  name: subfactionNames.COALESCED,

  // Example structure of a subfaction, imagine this repeated for traits, spells, etc
  units: {
      all: [], // These are all of the units available to this subfaction (Required)
      mandatory: [], // These are units that MUST exist in this subfaction (Optional)
      not_allowed: [], // These are units that MAY NOT exist in this subfaction (Optional)
  },
}


const starborneSubfaction = {}

// import AllSeraphonUnits from './units'
// import AllSeraphonBattalions from './units'
// import AllEtc from './AllEtc' /// traits spells etc

export const SeraphonFaction = {
  factionName,
  subFactions: [coalescedSubfaction, starborneSubfaction],

  // Export everything (to be used for imports/ally stuff)
  // units,
  // battalions,
  // etc,
}
```

**Comment by exonian** [comment]
```all: [], // These are all of the units available to this subfaction (Required)```
Is this precisely what this would be? Or would it actually just be the additional ones provided by the subfaction?

**Comment by daviseford** [comment]
```ts
import { keyOmitter, keyPicker } from './metatagger'
import { Units } from './units'

const subFactions = {
  COALESCED: {
    units: {},
  },

  // Example structure of a subfaction, imagine this repeated for traits, spells, etc
  STARBORNE: {
    units: {
      all: keyOmitter(Units, 'Lord Kroak'), // Let;s pretend we can't have Lord Kroak
      mandatory: keyPicker(Units, 'Bastiladon'), // pretend we need a bastiladon
      not_allowed: keyPicker(Units, 'Saurus Warriors', 'Skinks'), // and pretend we can't have a saurus gaurd oor skinks
    },
  },
}

export default subFactions
```

**Comment by daviseford** [comment]
I thinki I'm going to have Units (and things like it) be objects, rather than arrays
