### ISSUE TITLE
Figure out/Convert the various LoN factions/subfactions (DETAIL NEEDED FROM SUBJECT MATTER EXPERTS) to v4

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#1096]

**Comment by exonian** [comment]
WHAT DO YOU NEED TO KNOW?

**Comment by daviseford** [comment]
Can anyone offer a breakdown of how all of the Legions of * work together?
Are they all subfactions of Legions of Nagash?
I am looking to knock these out
rogue_michaelToday at 6:16 PM
@davis Legions of Night|Sacrament|Blood are, as is Soulblight. Legion of Grief is not. The three legions that are share a bunch of rules and each add their own little bits. Unsure how much Soulblight overlaps for allegiance abilities, but it's in the book and uses a subset of the same models

**Comment by exonian** [comment]
I edited on Discord but you'd already grabbed this. Grand Host of Nagash very much the same deal as the three Legions in the book.
