### ISSUE TITLE
v4: sub-mandatory selections not populating

### ISSUE THREAD

**Issue by JohnSchramm** [daviseford/aos-reminders#1133]
**Describe the bug**
Sub-mandatory options not being populated from super sets.  First noticed on super battalions pulling in regular battalions with mandatory fields.

**To Reproduce**
Currently not checked in but noticed while updating Nurgle to V4.

**Expected behavior**
Mandatory inclusions from sub choices should be populated as well.

**Screenshots**
![Sub-mandatory Bug](https://user-images.githubusercontent.com/53314953/101291802-a66bc680-37c8-11eb-9600-853622babf63.gif)

**Comment by daviseford** [comment]
I will investigate, ty sir
