### ISSUE TITLE
v4: Legion of Azgorh unit mandatory populations.

### ISSUE THREAD

**Issue by JohnSchramm** [daviseford/aos-reminders#1147]
**Describe the bug**
I may have done this to myself somehow in the last mad dash...
Legion of Azgorh unit selections are populating spells and command ability entries in the same area as units.

**To Reproduce**
Click on Legion of Azgorh units with spells/command abilities.

**Expected behavior**
The populated field should show up in the correct locations.  The entries exist, they just aren't being populated in the right location via mandatory.

**Screenshots**
![Auto Populate Bug](https://user-images.githubusercontent.com/53314953/101720713-8b68b300-3a63-11eb-872f-fbb9a64b4281.gif)

**Comment by exonian** [comment]
https://github.com/JohnSchramm/aos-reminders/blob/v4-beasts-of-chaos/src/factions/legion_of_azgorh/units.ts#L98
```units: [keyPicker(Spells, ['Ash Storm'])]```

Just a simple typo, fortunately: presumably a copy-paste from a battalion and you've just missed changing `units:` to the correct pick types.

**Comment by JohnSchramm** [comment]
Ah yep, that would do it.  I should have probably stopped at a different point last night but I wanted to push through... 

Thanks!
