### ISSUE TITLE
[QUESTION] Unit selection choices in grand alliance

### ISSUE THREAD

**Issue by thundergore** [daviseford/aos-reminders#1154]
Are the range of options right or something we'll look at once the factions structure is finalised?
 
E.g.

<img width="386" alt="Units selection" src="https://user-images.githubusercontent.com/52839060/101829830-ea95f880-3b33-11eb-8174-cd55de623ee8.PNG">

**Comment by thundergore** [comment]
Mawtribes actually have the same options - seems more like a bug (will fix) 

<img width="411" alt="Units selection (destruction)" src="https://user-images.githubusercontent.com/52839060/101829895-04374000-3b34-11eb-8ad3-0c88d9f773df.PNG">

**Comment by daviseford** [comment]
This raises a valid concern, but I will address it _after_ we've ported all of the data over.

**Comment by daviseford** [comment]
ixed
