### ISSUE TITLE
[BUG] Wrong rule attribution

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#1184]
Shouldn't this rule come from the Bonesplitterz subfaction?

<img width="1160" alt="Screen Shot 2020-12-23 at 6 19 59 PM" src="https://user-images.githubusercontent.com/9663863/103043637-90416280-454b-11eb-9565-2affa693d6c5.png">

**Comment by exonian** [comment]
Yes, I think in general we should attribute these rules to subfaction rather than faction. I'm trying to think of a case where that wouldn't be desirable. Stormcast is closest I've thought of so far, and I still think it's a good idea there

**Comment by daviseford** [comment]
Looks like a good candidate for a test suite :)
