### ISSUE TITLE
Deadly Hail is missing for Boulderhead

### ISSUE THREAD

**Issue by sedulam** [daviseford/aos-reminders#1188]
The "Deadly Hail" faction ability from the Boulderhead sub-faction (Ogor Mawtribes), is missing.

**To Reproduce**
1. Select Boulderhead, in the Mawtribes dropdown

**Expected behavior**
Deadly Hail should appear as one of the abilities (probably in the Hero Phase).

**Comment by exonian** [comment]
This is Done, @daviseford
