### ISSUE TITLE
[BUG] Cannot save army in Android Firefox

### ISSUE THREAD

**Issue by leahmangray** [daviseford/aos-reminders#1190]
In Android Firefox, I cannot save an army because the army name textbox and Save and Cancel buttons are not visible. It will not allow scrolling above the "Faction" section. The first screenshot shows the screen immediately after clicking Save. The textbox is focused but not visible (the keyboard becomes visible). The second shows after dismissing the keyboard. It allows scrolling just a bit farther up, but not far enough.

![Screenshot_1](https://user-images.githubusercontent.com/31160448/103955906-fcf05b80-510c-11eb-91ea-9701d1a806e4.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/31160448/103955910-fe218880-510c-11eb-8987-56bf10fcbb1d.jpg)

1. Load/Create an army
2. Click Save Army
3. Cannot access army name textbox or Save or Cancel buttons

I thought it might be due to my having android font size set at its highest, but I changed it to the default and had the same problem. Chrome worked fine at both font sizes.

**Comment by daviseford** [comment]
Thanks for this ticket! I will look into it :)
