### ISSUE TITLE
Grand alliance battle traits missing?

### ISSUE THREAD

**Issue by exonian** [daviseford/aos-reminders#1192]
**Faction:**
All Grand Alliances

**Name of the rule:**
Chaos: Unbridled Malice
Order: Defiant Avengers
Death: Deathless Minions
Destruction: Rampaging Destroyers

Haven't checked if this stuff is in the code but not being pulled through, or if it's just missing. Rules need to be defined as battle traits and then included as mandatory side effects on the default subfaction of each of these factions.

**Comment by daviseford** [comment]
they do not appear in the code 🤔
