### ISSUE TITLE
[BUG] Favorite faction sub-faction not reset

### ISSUE THREAD

**Issue by exonian** [daviseford/aos-reminders#1193]
**Describe the bug**
When loading the page without any selections, the favorite faction is selected. The sub-faction should be changed to the favorite faction's default sub-faction, but does not change

**To Reproduce**
1. Have a favorite faction set. It should have sub-factions, eg Stormcast
2. Select Cities of Sigmar (this faction has no mandatory selections so nothing should be added)
3. Refresh the page
4. Your favorite faction should be set but the sub-factions dropdown will have CITIES_OF_SIGMAR as the selected value

**Expected behavior**
Given that I think switching to favorite faction is intended in this situation (although I think that feature is much less needed since we got redux-persist), I think all that is needed is to trigger the setting of the subfaction when the favorite faction is invoked.

**Comment by exonian** [comment]
![image](https://user-images.githubusercontent.com/1237986/106633271-8d885300-6576-11eb-8a7c-f1b00132724b.png)
![image](https://user-images.githubusercontent.com/1237986/106633299-97aa5180-6576-11eb-975e-eba61994b946.png)

I glanced at the PR and wasn't sure which bit was fixing this issue, but I'm not sure it's worked

**Comment by daviseford** [comment]
I'm dumb. I fixed another issue that was _similar_ (blank subfaction name in the reminders) but it wasn't this.

Thanks for being smarter than me, as usual :D

**Comment by exonian** [comment]
Thoroughly not! I just saw that it was still there, nothing more!
