### ISSUE TITLE
Turn structure does not include round

### ISSUE THREAD

**Issue by grzegorzmiazga** [daviseford/aos-reminders#12]
There is difference between **Turn** and **Round** in AoS. For example Gloomspite Gitz have abilities working at end of turn **Bad Moon Loonshrine: Moonclan Lairs** and end of round (so both players tuns) **Da Moon Onna Stikk**. Now both of those abilities are listed under **End of Turn**.

**Comment by daviseford** [comment]
Good point - I'll add it in!
