### ISSUE TITLE
Add Gloomspite Gitz - Grimscuttle Tribe from WD459

### ISSUE THREAD

**Issue by wspencermiller** [daviseford/aos-reminders#1205]

**Comment by daviseford** [comment]
https://cdn.discordapp.com/attachments/599292504504008721/803670394107068466/image0.jpg

**Comment by wspencermiller** [comment]
![pg1](https://user-images.githubusercontent.com/2074137/105877685-db74e800-5fc5-11eb-8878-5e54ac501237.png)
![pg2](https://user-images.githubusercontent.com/2074137/105877687-dc0d7e80-5fc5-11eb-8948-77b8fa06499f.png)
