### ISSUE TITLE
Rune of Khaine incorrently added

### ISSUE THREAD

**Issue by xchagger** [daviseford/aos-reminders#1210]
[WarscrollBuilderList.pdf](https://github.com/daviseford/aos-reminders/files/5910035/WarscrollBuilderList.pdf)

The attached list does not contain the artifact "Rune of Khaine". Nut when uploaded, "Artifact - Rune of Khaine" is incorrectly added in section "Wound Allocation"

![image](https://user-images.githubusercontent.com/7968714/106579762-f6e97100-6538-11eb-8914-10d65274d391.png)

**Comment by daviseford** [comment]
Thanks!

**Comment by daviseford** [comment]
![image0](https://user-images.githubusercontent.com/9663863/106604507-bc2e0b80-652d-11eb-9dee-9fc6bd76cee0.png)

We add Rune of Khaine because of the Priestess of Khaine rule :)

**Comment by xchagger** [comment]
Its confusing, as both Rune of Khaine" artifact and "Rune of Khaine" prayer has the same name. The prayer is added correctly, but I do not have the artifact "Rune of Khaine" in the list.

![image](https://user-images.githubusercontent.com/7968714/106606305-e269a080-6559-11eb-813a-640fa811e1e2.png)
