### ISSUE TITLE
[INCORRECT-RULE] Possibly incorrect Khorne rule

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#1241]
Hi.

I believe this is wrong:

"
Khorne Allegiance - Summon Daemons of Khorne
Summoning Costs:

1 Exalted Greater Daemon of Khorne - 16 BTP, (8 BTP if in army)

"
I'd like the Exalted to only cost 8, but he costs 16.

**Comment by PixelTom** [comment]
Looking at his warscroll: https://www.forgeworld.co.uk/resources/fw_site/fw_pdfs/aos_warscrolls/Downloads-AoS/aos-warscroll-Exalted-Daemon-of-Khorne.pdf

He's 16 Blood Tithe Points (BTP). Normally the BTP limit you can have is 8, but that jumps to 16 if he is in your army.

Very silly Forgeworld rules...
