### ISSUE TITLE
[INCORRECT-RULE] Kharadron Overlords

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#1263]
> The flying transport rules for the Ironclad, look like they are showing the rules from the Frigate.  The Ironclad is max. 25 models, and can't fly high with 16 or more inside.

> The endrinmaster command ability "By Grugni I have my eye on you" is in the "During Hero Phase" section, The Endrinriggers heal ability is before it, in the "start of Hero phase" section.  But 'By Grugni' is supposed to be used before Endrinriggers use their heal.  (word salad, hope that makes sense)

**Comment by thundergore** [comment]
First part fixed in PR #1268

**Comment by PixelTom** [comment]
Looks like this one is resolved and can be closed.
