### ISSUE TITLE
[ADD-FACTION] New Soulblight book

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#1276]
Let me know who's interested in data entry for this book!

**Comment by Holger487** [comment]
im interested, and have already started to write alot of it down ready to be copy pasted

**Comment by daviseford** [comment]
@Holger487 I could use some help adding units to the existing PR I opened. If you want to open a PR against mine, please let me know :) https://github.com/daviseford/aos-reminders/pull/1280
