### ISSUE TITLE
[BUG] Adding a Freeguild General to a Cities of Sigmar army adds the whole spells list to the Spells section

### ISSUE THREAD

**Issue by tndines** [daviseford/aos-reminders#1341]
**Describe the bug**
Adding a Freeguild General to a Cities of Sigmar army adds the whole spells list to the Spells section.

**To Reproduce**
(On Firefox 89.0.2 (64-bit) )
1. In Edit mode, set army to Cities of Sigmar
2. Add "Freeguild General" to the Units section

**Expected behavior**
Onlt the CA should appear (which it does also)

**Screenshots**

**Additional context**
<3 mad impressed at 3.0 turnaround

**Comment by daviseford** [comment]
Looking into this now.
