### ISSUE TITLE
[BUG] Daemon Prince unit adds invalid command abilities

### ISSUE THREAD

**Issue by bszonye** [daviseford/aos-reminders#1361]
**Describe the bug**
When you add a Daemon Prince unit, the app automatically adds four command abilities to your roster: Arcane Influence, Bloated Blessings, Bloodslick Ground, and Revel in Agony. However, those abilities do not have valid reminder text in the app. The valid command abilities are called Arcane Influence: Tzeentch, Bloated Blessings: Nurgle, Bloodslick Ground: Khorne, and Revel in Agony: Slaanesh.

**To Reproduce**
1. Add the Daemon Prince unit to your roster.
2. See the four god-specific abilities appear in Command Abilities.
3. Scroll through the reminders; there are no reminders for those abilities.
4. Click on the Command Abilities drop-down and see the correct four abilities in the list. Adding any of these produces the correct reminder text.

**Expected behavior**
The Daemon Prince unit should add the four abilities that are correctly linked to reminder text.

**Comment by daviseford** [comment]
Thanks for the report. I'll look into this.

**Comment by bszonye** [comment]
Verified. Thanks!
