### ISSUE TITLE
[BUG] can’t add BeLakor

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#1372]
@daviseford
 I dont find a way to add my Belakor ally to my Slaanesh army. If I choose Slaves To Darkness and add him, he gets removed as soon as I change (back) to Slaanesh. 
Maybe you can add him to Slaanesh as well? 
Thanks for your work! :)

**Comment by thundergore** [comment]
This is no doubt also the case for Nurgle, Khorne & Tzeentch

**Comment by exonian** [comment]
Does the person just not know how to add allies in AoSR?
I've just tried it and it seems to work fine for me.

My guess is they're trying to add it like you would in wsb ie you switch the whole allegiance to add it and then mark it as an ally, rather than with AoSR's bespoke ally system.
