### ISSUE TITLE
[ADD-RULE] SoB rules from White Dwarf

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#1382]
Add the attached Sons of Behemat rules from White Dwarf

![3E3409DF-7FFC-4FEC-94C8-BD35D9135F4E](https://user-images.githubusercontent.com/9663863/130331198-d4dc1f77-83f1-43eb-8db3-8dab8f732001.png)
![696C6727-828F-4DAA-B9A6-37E0644084D9](https://user-images.githubusercontent.com/9663863/130331199-9b1fc63c-2401-4048-ae0c-5d55333c1ff6.png)
![54F5A119-31C8-4D0F-ADEA-3B49A91F8D2B](https://user-images.githubusercontent.com/9663863/130331201-b0361565-ed3c-4eea-89d5-2805d3f84ba2.png)

**Comment by daviseford** [comment]
Are these rules real? They have typos (Grand Stratergy)

**Comment by wspencermiller** [comment]
![IMG_5556](https://user-images.githubusercontent.com/2074137/130340787-bad659b6-0e65-4a30-b3e9-d77b09af7bc3.JPEG)
![IMG_5557](https://user-images.githubusercontent.com/2074137/130340788-37dcb863-1477-4363-8354-aa25d26d494a.JPEG)

**Comment by wspencermiller** [comment]
Here's the actual rules, working to get these in now

**Comment by daviseford** [comment]
Thanks. Let me know if you need help!

**Comment by wspencermiller** [comment]
Got sidetracked last night but will continue this PM
