### ISSUE TITLE
UX design of "jumbotron" element

### ISSUE THREAD

**Issue by thundergore** [daviseford/aos-reminders#139]
Low down on prio list but looking at UI space taken up by the jumbotron element/container, I feel like one could make better use of the space. 

![image](https://user-images.githubusercontent.com/52839060/62162372-6e24c000-b318-11e9-87b0-cffc2a9b8e49.png)

The more factions we add, the better the site, but this one area will get more cluttered. 

A simple text change fixes this in a quick and dirty way. 

A change in the UI (for example: the armies listed are listed "beautifully" and the faction is selected from that list & the dropdown is removed) is the elegant fix but isn't something I'm equipped to give decent feedback on :)

**Comment by thundergore** [comment]
I don't mind this:
![image](https://user-images.githubusercontent.com/52839060/62165039-d5913e80-b31d-11e9-93b9-3b6f96bc01bc.png)

Something to ponder anyway!

**Comment by daviseford** [comment]
Oooo I like this!
