### ISSUE TITLE
[INCORRECT-RULE] 

### ISSUE THREAD

**Issue by RBGM01** [daviseford/aos-reminders#1413]
**Eye of Sheerian**

**Correct Rule Text:**

>Once per battle, at the start of your hero phase, you can say that
Archaon will use the Eye of Sheerian. If you do so, subtract 1 from hit
rolls for attacks that target this unit until your next hero phase.’

**Comment by daviseford** [comment]
Hi RBGM01 , I believe this rule is already up to date in the codebase

See here: https://github.com/daviseford/aos-reminders/blob/141f2bf70fec7439c3909851c2640e93f418490a/src/factions/slaves_to_darkness/units.ts#L226
