### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by dougiebuckets998** [daviseford/aos-reminders#1442]
Warning: We couldn't find 'Aetherquartz Reserve, Alarith - Mountain Kindred, Helon, Hurakan - Kindred of the Winds, Scinari - Masters of the Teclamentari, Vanari - Warriors of Light'. It may be a typo or an ally item. Make sure to add it manually.

**Comment by daviseford** [comment]
This is an unfortunate artifact of the way Battlescribe constructs their HTML. It should be safe to ignore.
