### ISSUE TITLE
Unable to import a list from AOS App

### ISSUE THREAD

**Issue by chrisdenmark84** [daviseford/aos-reminders#1454]
Hello!

I've attempted to upload a list from the AOS app but get the following error.

Error: There was a problem parsing this text. Please try copy + pasting it again from the Warhammer App.

https://aos-reminders-error-logs.s3.amazonaws.com/prod/1640117854602-Warhammer_App.txt

- Army Faction: Stormcast Eternals 
- Army Type: Scions of the Storm
- Subfaction: Hallowed Knights
- Grand Strategy: Prized Sorcery
- Triumph: Inspired
LEADERS
Gardus Steel Soul (160)
Lord-Arcanum on Tauralon (285)
- Artefacts of Power: Mirrorshield
- Spells: Chain Lightning
Knight-Incantor (125)
- Spells: Celestial Blades
Lord-Relictor (145)
- General
- Command Traits: High Priest
- Artefacts of Power: Arcane Tome
- Spells: Thundershock
- Prayers: Translocation
BATTLELINE
5 x Liberators (115)
5 x Liberators (115)
5 x Liberators (115)
OTHER
4 x Dracothian Guard Fulminators (460)
6 x Vanguard-Raptors with Longstrike Crossbows (480)
CORE BATTALIONS
 -  Hunters of the Heartlands
 -  Vanguard
 -  Warlord
TOTAL POINTS: 2000/2000
Created with Warhammer Age of Sigmar: The App

**Comment by daviseford** [comment]
Looking into it now. Thanks for the detailed report!

**Comment by chrisdenmark84** [comment]
@daviseford Thank you for fixing that so quickly, that's really very kind of you!

I hope you have a great Christmas!
