### ISSUE TITLE
Metamorphosis spell is missing

### ISSUE THREAD

**Issue by sedulam** [daviseford/aos-reminders#1467]
**Faction:**  GHB 2021

**Name of the rule:** Metamorphosis

**Rule Text:** 

> Metamorphosis is a spell that has a casting value of 5 and a range of 12". If successfully cast, pick 1 friendly HERO that is not a MONSTER and that is within range and visible to the caster. That HERO gains the MONSTER keyword until your next hero phase.

**Comment by exonian** [comment]
It's not missing. You just have to select the Ghur realmscape from the "Realm of Battle" dropdown

**Comment by sedulam** [comment]
I did :) Any way to make a dump of the selection of dropdows? To share here

**Comment by sedulam** [comment]
Ah, never mind, it's added automatically on the script. I was looking at the boxes with blue headers. It doesn't show on the selected spells so I didn't notice it below. Thanks and sorry! :D
