### ISSUE TITLE
Sylvaneth Allegiance - Navigate Realmroots [INCORRECT-RULE] 

### ISSUE THREAD

**Issue by Tinky** [daviseford/aos-reminders#1503]
**Name of the rule:**
Sylvaneth Allegiance - Navigate Realmroots 

**Correct Rule Text:**

> Instead of making a normal move in your movement phase, 1 friendly Sylvaneth unit wholly within 6" of an Awakened Wyldwood can navigate the relamroots. If it does so, remove that unit from the battlefield and then set it up again wholly within 6" of another Awakend Wyldwood and more than 9" from any enemy units.

(From the App up to date as of the 1/04/22)

**Comment by Tinky** [comment]
This rule might need to be in a different phase.
Thanks

**Comment by daviseford** [comment]
Fixed, thanks @Tinky !
