### ISSUE TITLE
[ADD-RULE]  Nighthaunt Battletome

### ISSUE THREAD

**Issue by wspencermiller** [daviseford/aos-reminders#1520]
![image](https://user-images.githubusercontent.com/2074137/171323889-e8ab8912-52cc-4b15-a72a-affdd2d6b28e.png)
![image](https://user-images.githubusercontent.com/2074137/171323931-485c78ca-1685-4da9-ae2c-99ebd0961a18.png)

![image](https://user-images.githubusercontent.com/2074137/171323907-33e65dc2-fbe5-4d7f-bf6e-c05d93e6bfa9.png)
![image](https://user-images.githubusercontent.com/2074137/171323951-be6a8dda-3f4e-45ee-9def-dcc62f6459a7.png)

![image](https://user-images.githubusercontent.com/2074137/171323872-c3eda73f-e6e0-47ad-87ff-06e7c8a0f7f9.png)

![image](https://user-images.githubusercontent.com/2074137/171323861-ea4f53a7-f21b-4b18-bc92-f20b5e313474.png)

**Comment by daviseford** [comment]
Thank you!
