### ISSUE TITLE
New Flesh Eater Courts rule in white dwarf

### ISSUE THREAD

**Issue by megaBossMike** [daviseford/aos-reminders#1523]
Screenshot sent to your discord

> New heroic action
> new battle tactics and grand strategy
> new terrain rules for throne

Maybe more to come when released.

**Comment by daviseford** [comment]
https://cdn.discordapp.com/attachments/930105716352634972/984873881057759232/unknown.png

https://cdn.discordapp.com/attachments/930105716352634972/984873881582059580/unknown.png

https://cdn.discordapp.com/attachments/930105716352634972/984873881909231666/unknown.png
