### ISSUE TITLE
[ADD-RULE] Disciples of Tzeentch BT 3.0

### ISSUE THREAD

**Issue by wspencermiller** [daviseford/aos-reminders#1552]
**Faction:**

**Name of the rule:**

**Rule Text:**

> During your hero phase... etc

**Comment by wspencermiller** [comment]
Adding Disciples of Tzeentch
- keeping all Tzeentch named export/imports
- finished with allegiance abilities including spell lore, traits, tactics, grand strats, etc

To Do:
- Add unit changes

**Comment by daviseford** [comment]
This was already done I believe.
