### ISSUE TITLE
[Skaven missing prayers]

### ISSUE THREAD

**Issue by awijntje** [daviseford/aos-reminders#1595]
Skaven

Prayer: Disease-Disease!

![20230208_190942.jpg](https://user-images.githubusercontent.com/1772781/217615768-d1b7a59a-a1e8-455b-9974-babe3754796c.jpg)

Prayer: Filth-filth!

![20230208_191152.jpg](https://user-images.githubusercontent.com/1772781/217616443-7adbffaf-d0d9-4fc6-bfca-56b2cd00d435.jpg)

Prayer: Rabid-rabid!

![20230208_191202.jpg](https://user-images.githubusercontent.com/1772781/217616505-e68294e9-e3d4-45cb-afe5-0d8245b80d19.jpg)

**Comment by daviseford** [comment]
Working on this. It's a bug. Thanks for the report!
