### ISSUE TITLE
Add spells/endless spells for factions

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#160]
The following factions need Spells added:

+ **Idoneth Deepkin**

Please submit PR's for any and all of these when you can! 

The following factions need to have Endless spells added:

+ **Idoneth Deepkin**
  + (do they have endless spells?)

**Comment by thundergore** [comment]
PR for SC including spells and endless spells submitted

**Comment by JohnSchramm** [comment]
Sorry should not have put "Fixed" into the comments!  It should be reopened.  There are still a few factions that need this treatment.  I'll put in placeholder files for the remaining factions that don't have spell lores/endless spells yet.  Here are the factions that still need this update and actually have content to fill in:

FEC
Gloomspite Gitz
Idoneth Deepkin
Skaven

**Comment by wspencermiller** [comment]
Idoneth do not have endless spells, not sure about spell lores

**Comment by Zirhark** [comment]
Created a pull request for the IDK lore spells. https://github.com/daviseford/aos-reminders/pull/227
