### ISSUE TITLE
[BUG] No entry for Saurus Oldblood on Carnosaur 

### ISSUE THREAD

**Issue by mattalhonte** [daviseford/aos-reminders#1632]
**Describe the bug**
Tried to import my list from AoS app, which includes a Saurus Oldblood on Carnosaur. It gave me an error. Then I looked at the dropdown and there wasn't an entry for it. 
description of what you expected to happen.

**Screenshots**

**Additional context**

**Comment by rfrank14** [comment]
@daviseford this can be closed as its fixed in #1637
