### ISSUE TITLE
[BUG] Be'lakor The Dark Master ability is worded incorrectly 

### ISSUE THREAD

**Issue by johnvmontoya** [daviseford/aos-reminders#1633]
**Describe the bug**
Be'lakor's The Dark Master ability is worded incorrectly. Should be "At the start of the enemy hero phase"

**To Reproduce** (current wording)
"Once per battle, pick 1 enemy unit on the battlefield. Starting now and until your next hero phase, roll a D6 at the start of each phase. On a 3+ the target cannot move, shoot, fight, use command abilities, chant prayers, or cast/dispell/unbind spells in that phase."

**Expected behavior**
"Once per battle, at the start of the enemy hero phase, pick 1 enemy unit on the battlefield. Starting now and until your next hero phase, roll a D6 at the start of each phase. On a 3+ the target cannot move, shoot, fight, use command abilities, chant prayers, or cast/dispell/unbind spells in that phase."

**Screenshots**
N/A

**Additional context**
N/A

**Comment by rfrank14** [comment]
@daviseford this can be closed as it was fixed in #1634
