### ISSUE TITLE
Print render is cut off for long sections in Firefox

### ISSUE THREAD

**Issue by Dantedeth** [daviseford/aos-reminders#170]
After 18 abilities (one whole page of text) the During hero phase page cuts off and does not continue printing on a next page

**Comment by daviseford** [comment]
Thanks, I’ll take a look at this!

**Comment by daviseford** [comment]
Working on it now

**Comment by daviseford** [comment]
Can I ask what browser you're using? I'm having trouble replicating this with Chrome. When I add a bunch of units and get a Hero Phase that takes up more than a page, it does overrun to the next page.

<img width="450" alt="Screen Shot 2019-08-03 at 9 59 02 PM" src="https://user-images.githubusercontent.com/9663863/62418570-151b9b80-b63a-11e9-82a5-087617f6cfa7.png">

**Comment by daviseford** [comment]
Unable to replicate using Safari as well

**Comment by Dantedeth** [comment]
I have the issue in Firefox,

**Comment by daviseford** [comment]
Perfect. Confirmed the issue on firefox

<img width="832" alt="Screen Shot 2019-08-04 at 4 55 18 PM" src="https://user-images.githubusercontent.com/9663863/62429134-b1947b00-b6d8-11e9-9111-2686c1c975da.png">

**Comment by daviseford** [comment]
According to MDN, [the "orphan" CSS property is not supported by Firefox](https://developer.mozilla.org/en-US/docs/Web/CSS/orphans)

We use the `orphan` property to handle rendering for print. Hmm 🤔.

**Comment by daviseford** [comment]
For the time being, I've just added a warning to Firefox users. They make up 6% of the app's users, so I don't want to leave them stranded long-term, but doing this warning is quicker than any other solution I can think of.

Firefox users will see a warning sign on the "Print Page" button. If they hover over it, they will see the following pop-up:

<img width="476" alt="Screen Shot 2019-08-04 at 10 35 08 PM" src="https://user-images.githubusercontent.com/9663863/62434908-511d3200-b708-11e9-8980-e51e3e082687.png">

**Comment by Dantedeth** [comment]
thanks for the feedback Davise! your website is very usefull :) you just one me my first match in a long time 👍
