### ISSUE TITLE
Leave Ability name and source unit but remove full text

### ISSUE THREAD

**Issue by thundergore** [daviseford/aos-reminders#173]
In some armies, you might take 2 (or more) units who have the same ability. You wouldn't want to include the text for the ability twice, but you might want to include the name of it and the 2nd unit (and so on) that can also use the same ability in a phase. 

Example

SC, Lord Celestant on Stardrake and Drakesworn Templar - their mounts share the same abilities in Shooting and combat phase.  

![remove bt leave the single ability line](https://user-images.githubusercontent.com/52839060/62398797-02419200-b57a-11e9-9d46-d519d8c2e18a.PNG)

Right now we can trim the reminders but that trims the entire entry in the resulting PDF.
![result now in pdf](https://user-images.githubusercontent.com/52839060/62398798-02419200-b57a-11e9-8cc6-078d011f8419.PNG)

If the final printout could show what the website shows (see [remove bt leave the single ability line]), it may be beneficial to some. 
![remove bt leave the single ability line 2](https://user-images.githubusercontent.com/52839060/62398796-02419200-b57a-11e9-8f41-38370458e26c.PNG)

**Comment by ctcodie** [comment]
Ran in to a similar issue earlier with the Kurnoth Hunters and Spite/Tree-Revenants for Sylvaneth. Multiple warscrolls with shared abilities, distinguished only by one extra ability.

**Comment by daviseford** [comment]
Good call. I can work on this. Only thing I wonder is how it will affect performance... 🤔 I’ll see how it goes!

**Comment by thundergore** [comment]
Is it something that could be related to dynamic reordering of elements? Kill two birds with one stone.

Like an "edit and review" stage pre-print

**Comment by daviseford** [comment]
It might be. I have been thinking for a while about refactoring the `addToGame`/`processReminder` functions - this would be a good time to do it!

**Comment by daviseford** [comment]
Fixed with #182 .

When two units share a similar effect name, their entry is combined.

Example, using the initial post in this issue:

<img width="1120" alt="Screen Shot 2019-08-04 at 12 43 37 AM" src="https://user-images.githubusercontent.com/9663863/62419576-2a4ff480-b651-11e9-8398-0fc8243e86e5.png">
