### ISSUE TITLE
Units with shared ability names are missing some other ability reminders

### ISSUE THREAD

**Issue by thundergore** [daviseford/aos-reminders#183]
Not sure of the exact interaction that causes it yet. 

PR #182 for fix #173 seems to have introduced it. 

Example I've checked - LCoSD and Drakesworn Templar - the shared shooting phase ability, some of the LCoSD combat phase abilities and most of the Drakesworn Templar's combat phase abilities (such as weapon choices) are missing:

![combat phase](https://user-images.githubusercontent.com/52839060/62420898-40ce6e00-b69a-11e9-99c1-c8065f6956fe.PNG)
![shooting phase](https://user-images.githubusercontent.com/52839060/62420899-40ce6e00-b69a-11e9-9def-d437388ed6c7.PNG)

**Comment by thundergore** [comment]
Their entires in units.ts on live site seem correct anyway:

`{
    name: `Lord-Celestant on Stardrake`,
    effects: [
      {
        name: `Arcane Lineage`,
        desc: `Add 1 to casting rolls for friendly WIZARDS while they are within 18" of this model. In addition, subtract 1 from casting rolls for enemy WIZARDS while they are within 18" of this model.`,
        when: [HERO_PHASE],
      },
      {
        name: `Cavernous Jaws`,
        desc: `After this model makes a pile-in move, this model's Stardrake can bite one or more enemy models with its cavernous jaws. The number of bites it can make is shown on the damage table above. For each bite, pick one enemy model within 3" of this model and roll a dice. If the roll is greater than that model's Wounds characteristic, it is slain.`,
        when: [COMBAT_PHASE],
      },
      {
        name: `Inescapable Vengeance`,
        desc: `Add D3 to the Attacks of this model's Celestine Hammer or Stormbound Blade if this model made a charge move in the same turn.`,
        when: [COMBAT_PHASE],
      },
      {
        name: `Sigmarite Thundershield`,
        desc: `Re-roll save rolls of 1 for this model. If the re-rolled save is successful, each enemy unit within 3" of this model suffers 1 mortal wound.`,
        when: [SHOOTING_PHASE, COMBAT_PHASE],
      },
      {
        name: `Lord of the Heavens`,
        desc: `This model can either breathe a Roiling Thunderhead or call down a Rain of Stars. If it breathes a Roiling Thunderhead, pick 1 enemy unit within 18" of this model that is visible to it. Roll a dice for each model in that unit that is within 18" of this model. For each 6+ that unit suffers 1 mortal wound.If it calls down a Rain of Stars, pick up to D6 enemy units on the battlefield. Roll a dice for each unit you pick. On a 4+ that unit suffers D3 mortal wounds.`,
        when: [SHOOTING_PHASE],
      },
      {
        name: `Sweeping Tail`,
        desc: `Each time this model attacks, roll a dice for each enemy unit within 3" of this model after all of this model's attacks have been resolved. If the roll is less than the number of models in that enemy unit, that enemy unit suffers D3 mortal wounds.`,
        when: [COMBAT_PHASE],
      },
      {
        name: `Stormbound Blade`,
        desc: `If the unmodified hit roll for an attack made with a Stormbound Blade is 6, that attack inflicts 3 hits on the target instead of 1. Make a wound and save roll for each hit.`,
        when: [COMBAT_PHASE],
      },
      {
        name: `Lord of the Celestial Host`,
        desc: `Re-roll failed wound rolls for attacks made by friendly STARDRAKE and DRACOTH mounts until the end of that phase.`,
        when: [START_OF_COMBAT_PHASE],
        command_ability: true,
      },`

& 

`{
    name: `Drakesworn Templar`,
    effects: [
      {
        name: `Arc Hammer`,
        desc: `If the unmodified hit roll for an attack made with an Arc Hammer is 6, that attack inflicts 2 hits on the target instead of 1. Make a wound and save roll for each hit.`,
        when: [COMBAT_PHASE],
      },
      {
        name: `Skybolt Bow`,
        desc: `If you score one or more hits on an enemy unit with this model's Skybolt Bow, add 1 to hit rolls for attacks made by friendly DRACOTHIAN GUARD units that target that enemy unit until the end of that turn.`,
        when: [SHOOTING_PHASE],
      },
      {
        name: `Stormlance`,
        desc: `If the unmodified hit roll for an attack made with a Stormlance that targets a MONSTER is 6, that attack inflicts D6 mortal wounds on the target and the attack sequence ends (do not make a wound or save roll).`,
        when: [COMBAT_PHASE],
      },
      {
        name: `Tempest Axe`,
        desc: `Subtract 2" from the distance enemy units can pile in when they start that pile-in move within 3" of this model.`,
        when: [COMBAT_PHASE],
      },
      {
        name: `Arcane Lineage`,
        desc: `Add 1 to casting rolls for friendly WIZARDS while they are within 18" of this model. In addition, subtract 1 from casting rolls for enemy WIZARDS while they are within 18" of this model.`,
        when: [HERO_PHASE],
      },
      {
        name: `Cavernous Jaws`,
        desc: `After this model makes a pile-in move, this model's Stardrake can bite one or more enemy models with its cavernous jaws. The number of bites it can make is shown on the damage table above. For each bite, pick one enemy model within 3" of this model and roll a dice. If the roll is greater than that model's Wounds characteristic, it is slain.`,
        when: [COMBAT_PHASE],
      },
      {
        name: `Lord of the Heavens`,
        desc: `This model can either breathe a Roiling Thunderhead or call down a Rain of Stars. If it breathes a Roiling Thunderhead, pick 1 enemy unit within 18" of this model that is visible to it. Roll a dice for each model in that unit that is within 18" of this model. For each 6+ that unit suffers 1 mortal wound.If it calls down a Rain of Stars, pick up to D6 enemy units on the battlefield. Roll a dice for each unit you pick. On a 4+ that unit suffers D3 mortal wounds.`,
        when: [SHOOTING_PHASE],
      },
      {
        name: `Sweeping Tail`,
        desc: `Each time this model attacks, roll a dice for each enemy unit within 3" of this model after all of this model's attacks have been resolved. If the roll is less than the number of models in that enemy unit, that enemy unit suffers D3 mortal wounds.`,
        when: [COMBAT_PHASE],
      },
    ],
  },`

**Comment by daviseford** [comment]
Will check it out

**Comment by daviseford** [comment]
I have reverted the commit that caused this behavior in the meantime so that our live site is not affected.

**Comment by daviseford** [comment]
I have fixed this issue (just a small bug in the code I wrote at 1am, who would have thought 🙄 )

I also added a test suite for `processReminders` so this won't happen again :)
