### ISSUE TITLE
Add Beasts of Chaos

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#197]

**Comment by LiuSeeker** [comment]
I'm on it

**Comment by LiuSeeker** [comment]
Where can I find something about traits and artifacts?

**Comment by daviseford** [comment]
Looks like all of that starts at page 61 in my BoC battletome.

<img width="290" alt="Screen Shot 2019-08-08 at 8 36 22 AM" src="https://user-images.githubusercontent.com/9663863/62703646-a2068200-b9b7-11e9-927f-795e74a27e5f.png">

Hop on the Discord if you want to chat! https://discord.gg/2nt9Fxp

**Comment by LiuSeeker** [comment]
Can I get this battletome somewhere online for free?

**Comment by daviseford** [comment]
https://mega.nz/#F!6EZEHQqJ!gdDBPH48LYPGDccS4YaeWA

**Comment by LiuSeeker** [comment]
Thanks
