### ISSUE TITLE
Request: Add Slaanesh weapon options

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#217]
> Being able to select which weapon the Keeper of Secrets and similar units have would be useful. I didn't find a way to do it, but I'm also on mobile.

**Comment by thundergore** [comment]
Where SCE units had weapon options I added them all and the users can remove them. I wonder if thats what you mean or are you thinking new feature?

EG LCoD (4 options):

`{
    name: `Lord-Celestant on Dracoth`,
    effects: [
      {
        name: `Lightning Hammer`,
        desc: `If the unmodified hit roll for an attack made with a Lightning Hammer is 6, that attack inflicts 2 mortal wounds on the target in addition to its normal damage. If a unit suffers any mortal wounds in this way, it cannot pile in later that phase.`,
        when: [COMBAT_PHASE],
      },
      {
        name: `Stormstrike Glaive`,
        desc: `Add 2 to the Damage of this model's Stormstrike Glaive if this model made a charge move in the same turn.`,
        when: [COMBAT_PHASE],
      },
      {
        name: `Tempestos Hammer`,
        desc: `Add D3 to the Attacks of this model's Tempestos Hammer if this model made a charge move in the same turn.`,
        when: [COMBAT_PHASE],
      },
      {
        name: `Thunderaxe`,
        desc: `Add 1 to the Attacks of this model's Thunderaxe for each other friendly STORMCAST ETERNAL unit wholly within 9" of this model when the attack is made.`,
        when: [COMBAT_PHASE],
      },
    ],
  },`

**Comment by daviseford** [comment]
Yeah just add them as you stated

**Comment by daviseford** [comment]
Just checked - these weapon options are already there. I guess we could split them into three types of KoS? I will do that.
