### ISSUE TITLE
Distinguish army realm origin from battlefield realmscape.

### ISSUE THREAD

**Issue by JohnSchramm** [daviseford/aos-reminders#228]
This will make more sense with my commit.  Basically we need to separate the realmscape battlefield the game is taking place in vs where the army list was built from.  

This change will require adding an additional selection box somewhere for where the army hails from.  This box should then alter the contents of the realm spells and artifacts selection menus.  Similar to how the realmscape menu currently works.

I am adding separate files for battlefield realmscape abilities/spells into the generic folder to (hopefully) help deal with this.

**Comment by Zirhark** [comment]
Only the artifacts are impacted by which realm you hail from, the spells you can cast are based on which realm the battle is taking place in.

**Comment by JohnSchramm** [comment]
Yeah good point.  I'll merge the separate realm spells into the realmscape spells file so they are bundled together with the other realmscape effects.
