### ISSUE TITLE
Automatically add spells when adding a spell caster

### ISSUE THREAD

**Issue by Zirhark** [daviseford/aos-reminders#232]
Depends if you all think this is useful. Perhaps add a way to attach spells to a caster unit, so that their warscroll spell can be included but still indicate that it is a spell. 

It might make sense to store it with the units.ts instead of in the spells.ts.

**Comment by daviseford** [comment]
Some casters do have their spells attached to them in `units.ts`. I think that's all we really need to do for now. There's no harm in having them in both places, but this is something to think about down the line.
