### ISSUE TITLE
Allow users to enter custom reminders

### ISSUE THREAD

**Issue by wspencermiller** [daviseford/aos-reminders#260]
Allowing the user to add a custom reminder on their own list before printing. eg:
During Combat Phase
+ Add Reminder
- Name: "Casualties"
- Description: "Leave casualties on near the unit so you can better count battleshock"

Quick Mockup:
![image](https://user-images.githubusercontent.com/2074137/63204050-9a02ae00-c059-11e9-96d0-f2b6448151eb.png)

**Comment by Flui** [comment]
I think this relates to #576 as there could be used the same richtext editor to create and to edit a reminder

**Comment by daviseford** [comment]
Fixed by #1064
