### ISSUE TITLE
Add allegiances that are unlocked via battalions with other battle tomes

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#271]
From Discord user Grunt9101

> anyway to be able to have allegiances that are unlocked via battalions with other battle tomes?

> for example, my Beasts of Chaos running as Nurgle, if I use the Pestilent Throng battalion.

![2019-8-20_10-3-14](https://user-images.githubusercontent.com/9663863/63357219-108ffc00-c337-11e9-9374-ca63f620847a.png)

> well first place is the battalions in the BoC book- they list that the Beasts of Chaos untis in the battalion all gain the appropriate keywords.

> then 2nd part, is the FAQ, which i'll screen shot quick

> Here's the clarification for how BoC work

![Screenshot_20190820-104207](https://user-images.githubusercontent.com/9663863/63357424-65337700-c337-11e9-851f-c76f3d883a27.png)

![unknown](https://user-images.githubusercontent.com/9663863/63357582-a88de580-c337-11e9-8997-00c346da848d.png)

> and here's a screen shot of how the battalions in the Battle tome work.

**Comment by Zirhark** [comment]
You can assign this to me.
