### ISSUE TITLE
Split out LoN legions

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#303]
> Can I request one day to have the Legions of Nagash Legions separated out into Host/Sacrament/Blood/Night and Soulblight? That is, if you’re not already doing it.

Also covers #293

**Comment by wspencermiller** [comment]
Does this need to be separate armies or should they stay under the "Legions of Nagash" banner? It feels 6 one way, half a dozen the other

**Comment by daviseford** [comment]
@wspencermiller I have gotten quite a few people asking me to add the various sublegions, so this will clear up confusion

**Comment by Zirhark** [comment]
Assign to me pls.
