### ISSUE TITLE
Add the ability to create reminders based on imported BattleScribe roster

### ISSUE THREAD

**Issue by RedBishop777** [daviseford/aos-reminders#307]
Feature suggestion

Having the ability to import and parse an existing roster from BattleScribe in order to generate to proper reminders automatically would be great!

Cheers, thanks for your work!

**Comment by daviseford** [comment]
That is a great idea :) I will have to check out Battlescribe to see how I can get this to work. Do you have an example of an export from Battlescribe?

**Comment by daviseford** [comment]
[BattleScribe_Outputs.zip](https://github.com/daviseford/aos-reminders/files/3557009/BattleScribe_Outputs.zip)

**Comment by daviseford** [comment]
Will need a lot of Battlescribe lists to get this one started
