### ISSUE TITLE
Add Ossiarch Bonelords

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#308]

**Comment by Zirhark** [comment]
Assign to me pls

**Comment by daviseford** [comment]
Thanks to @Zirhark we have the bones of this army (hehe) laid out. Waiting for more details to improve them!

**Comment by Zirhark** [comment]
#345  was the first pull of this. Won't be the last.

**Comment by Zirhark** [comment]
https://www.warhammer-community.com/2019/10/24/ossiarch-bonereapers-the-sub-factionsgw-homepage-post-1/
