### ISSUE TITLE
Add ability to import warscrollbuilder lists from the text summary

### ISSUE THREAD

**Issue by exonian** [daviseford/aos-reminders#354]
I mostly use warscrollbuilder with the "Army summary" text export rather than the pdf generation, which I then will usually have on my clipboard if it's straight away, or in a chat history, but not as a downloaded file.

It would be really useful to me to be able to import from this as well as the pdf, ideally by pasting straight into a text input.

Example list attached
[stormcast_2k.txt](https://github.com/daviseford/aos-reminders/files/3595301/stormcast_2k.txt)

**Comment by daviseford** [comment]
Should be a pretty easy lift, considering the text output is nearly identical to the PDF!
