### ISSUE TITLE
Missing batallion (Skyborne Slayers) and missing stormhost artifacts / command abilities

### ISSUE THREAD

**Issue by Brucimus83** [daviseford/aos-reminders#365]
Hi,

As mentioned in the title, Skyborne slayers is missing, and the stormhost artifacts and command abilities and traits are not found.

Batallion warscroll
https://www.games-workshop.com/resources/PDF/AoS_Warscrolls/aos-warscroll-skyborneslayers-en.pdf

And my imported warscroll builder list.
[Skyborne.pdf](https://github.com/daviseford/aos-reminders/files/3596184/Skyborne.pdf)

**Comment by daviseford** [comment]
Thanks! Will get on this

**Comment by exonian** [comment]
I'm still getting the second described behaviour, with the (stormhost-specific) artefact and trait not importing. Is that bit a duplicate/by-product of #326?
