### ISSUE TITLE
Warscroll builder import is setting the realmscape

### ISSUE THREAD

**Issue by exonian** [daviseford/aos-reminders#367]
I don't think it should be setting the realmscape, as the army's home realm is a different thing. And, as all of the realm artefacts are available from the dropdown anyway, I don't think it needs it (my first thought was it might be a workaround for that).

**Comment by daviseford** [comment]
Good point.

**Comment by daviseford** [comment]
I was so proud that I had extracted the home realm from the PDF that I forgot it doesn't really matter for Reminders :D :D :D
