### ISSUE TITLE
Different Export Options

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#371]
> While you're at it with nothing better to put on your backlog you should create some kind of export text thing. Copy / Paste didn't go so well when I was trying to make little cards for myself out of your output. It would be rad to have a few different format options.

**Comment by exonian** [comment]
![paste_without_formatting](https://user-images.githubusercontent.com/1237986/86061335-85a38600-ba5e-11ea-8d94-b38645f831fd.PNG)

Not averse to doing something like  this, but I thought I'd just try Paste Without Formatting and it worked perfectly well so maybe there's less need for it?
