### ISSUE TITLE
Import of the "short" text summary from warscrollbuilder

### ISSUE THREAD

**Issue by exonian** [daviseford/aos-reminders#372]
Currently finds artefacts, spells, traits etc but not the units
[stormcast_short.txt](https://github.com/daviseford/aos-reminders/files/3597673/stormcast_short.txt)

**Comment by daviseford** [comment]
This may be a bit more difficult to accomplish, since the short version of the output does not have any way of demarcating Units vs Battalions/Spells/etc

**Comment by daviseford** [comment]
> Yeah totally reasonable, I was just curious about it. Maybe a warning message for the user (like for an unrecognised item in an import) would be useful. Cos I imagine detecting that there were no unit headers is pretty feasible?
