### ISSUE TITLE
Add ability to import lists from Azyr PDFs

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#383]
If anyone has Azyr, can they drop a sample PDF in here so I can look at it?

**Comment by exonian** [comment]
[Cats and Judicators 2000.pdf](https://github.com/daviseford/aos-reminders/files/3600682/Cats.and.Judicators.2000.pdf)

**Comment by daviseford** [comment]
@exonian could you do one with allies as well please? Want to see how they mark them up

**Comment by exonian** [comment]
[Army with allies.pdf](https://github.com/daviseford/aos-reminders/files/3613062/Army.with.allies.pdf)

**Comment by exonian** [comment]
Also threw in a stormhost on this one so you can see how they do sub-factions too

**Comment by daviseford** [comment]
Thanks! If you get the chance, other armies like

+ Slaanesh
+ KO
+ Destruction Grand Alliance

Those would be much appreciated!

**Comment by exonian** [comment]
[destruction.pdf](https://github.com/daviseford/aos-reminders/files/3613107/destruction.pdf)
[KO.pdf](https://github.com/daviseford/aos-reminders/files/3613108/KO.pdf)
[KO custom skyport.pdf](https://github.com/daviseford/aos-reminders/files/3613109/KO.custom.skyport.pdf)
[Slaanesh with mercenaries.pdf](https://github.com/daviseford/aos-reminders/files/3613110/Slaanesh.with.mercenaries.pdf)
[Stormcast open play with battalion.pdf](https://github.com/daviseford/aos-reminders/files/3613111/Stormcast.open.play.with.battalion.pdf)
[Fyreslayers ME.pdf](https://github.com/daviseford/aos-reminders/files/3613112/Fyreslayers.ME.pdf)

Not really certain what will be useful to you so tried to get a good variety of stuff, let me know if there's specifics I should be hitting. I tried adding a penumbral engine to one list but it didn't show up in the pdf 😅

**Comment by exonian** [comment]
Huh, the custom skyport info didn't export either

**Comment by daviseford** [comment]
@exonian can you do a Seraphon army with at least two battalions? Doesn't need to be valid

**Comment by exonian** [comment]
[Seraphon.pdf](https://github.com/daviseford/aos-reminders/files/3613818/Seraphon.pdf)

**Comment by exonian** [comment]
[Realms none.pdf](https://github.com/daviseford/aos-reminders/files/3613884/Realms.none.pdf)
[Realms shyish.pdf](https://github.com/daviseford/aos-reminders/files/3613885/Realms.shyish.pdf)
[Realms aqshy.pdf](https://github.com/daviseford/aos-reminders/files/3613886/Realms.aqshy.pdf)
[Realms chamon.pdf](https://github.com/daviseford/aos-reminders/files/3613887/Realms.chamon.pdf)
[Realms ghur.pdf](https://github.com/daviseford/aos-reminders/files/3613888/Realms.ghur.pdf)
[Realms ghyran.pdf](https://github.com/daviseford/aos-reminders/files/3613889/Realms.ghyran.pdf)
[Realms hysh.pdf](https://github.com/daviseford/aos-reminders/files/3613890/Realms.hysh.pdf)
[Realms ulgu.pdf](https://github.com/daviseford/aos-reminders/files/3613891/Realms.ulgu.pdf)

**Comment by Kleppa** [comment]
[No vortex, 2 bells  (2).pdf](https://github.com/daviseford/aos-reminders/files/3614241/No.vortex.2.bells.2.pdf)

**Comment by daviseford** [comment]
Thanks @Kleppa !

**Comment by exonian** [comment]
[LoG.pdf](https://github.com/daviseford/aos-reminders/files/3614266/LoG.pdf)
[IJ.pdf](https://github.com/daviseford/aos-reminders/files/3614269/IJ.pdf)

**Comment by exonian** [comment]
[KO plus.pdf](https://github.com/daviseford/aos-reminders/files/3615782/KO.plus.pdf)
Whole lotta endrinriggers to get that allies allowance, cos the one for every four rule is a thing that Azyr enforces unflinchingly...
Also wanted to include an allied battalion (that's legal, right!?) and Azyr doesn't seem to allow that (or most allegiances in grand alliance lists)

**Comment by daviseford** [comment]
I thought you could only do allied units, not battalions, but 🤷‍♀️

**Comment by exonian** [comment]
I'm probably just getting confused with battalions that include allies

**Comment by exonian** [comment]
[Nurgle.pdf](https://github.com/daviseford/aos-reminders/files/3617343/Nurgle.pdf)
[Tzeentch.pdf](https://github.com/daviseford/aos-reminders/files/3617418/Tzeentch.pdf)
[Khorne.pdf](https://github.com/daviseford/aos-reminders/files/3617420/Khorne.pdf)
[GHoN.pdf](https://github.com/daviseford/aos-reminders/files/3617423/GHoN.pdf)
[Beasts.pdf](https://github.com/daviseford/aos-reminders/files/3617440/Beasts.pdf)

**Comment by exonian** [comment]
Oh and I had to look up the battalions thing cos it was driving me mad. It's clarified in an FAQ
https://www.warhammer-community.com/wp-content/uploads/2018/12/age_of_sigmar_core_rules_designers_commentary_en-1.pdf
Page 9, the long question and answer on the right
