### ISSUE TITLE
Add Hedonites of Slaanesh

### ISSUE THREAD

**Issue by tlamphier23** [daviseford/aos-reminders#42]
This looks amazing and I would contribute if I could.  I am a new player and forget things all the time.  Great work so far

**Comment by daviseford** [comment]
Thanks for the feedback! Will definitely be adding Slaneesh in the future!

**Comment by JohnSchramm** [comment]
Just letting folks know I'm planning to jump onto this now unless someone else is already on it and much further along ;).

**Comment by daviseford** [comment]
> Just letting folks know I'm planning to jump onto this now unless someone else is already on it and much further along ;).

Go for it!
