### ISSUE TITLE
Add an option to include early game rules

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#421]
![8AC133AF-2EDE-477F-8EA9-C9C48DAB6AF7](https://user-images.githubusercontent.com/9663863/64931669-0105b500-d808-11e9-8a18-1e80d5c3dd8f.jpeg)

Brilliant idea from Dan at AoS Shorts

**Comment by exonian** [comment]
> Reading through the core rules, it looks like I managed to forget the bravery boost for large units in the battleshock phase, and so did every one of my opponents in the tournament last weekend

This rule feels like a candidate for the same potential enhancement as these start-of-game rules
