### ISSUE TITLE
Add Lynus Ghalmorian

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#450]
Named Lord Arcanum on Gryph-Charger for the Anvils of the Heldenhammer, found in the August 2019 White Dwarf.

**Comment by exonian** [comment]
?
https://github.com/daviseford/aos-reminders/blob/3ae0b494b1215327f5b787a7c08c3b15aa3f2afc/src/army/stormcast_eternals/units.ts#L1401

**Comment by daviseford** [comment]
Ah, I was getting `Lynus Ghalmorian on Gryph-Charger` from WSB, time to figure out what's right
