### ISSUE TITLE
Loading does not unset Realm or Realmscape

### ISSUE THREAD

**Issue by exonian** [daviseford/aos-reminders#486]
If the loaded army has saved values for these, it overrides whatever is currently in play.
However, if the loaded army has no saved value for them, they are not unset from their current values.

This appears to be the same behaviour exhibited when switching between factions, where everything else (fields I'd consider army-specific but also generic command abilities and triumphs) resets but these fields don't.

I'm not sure if either is strictly a problem, but it had me confused for a while when I was testing army updating!

**Comment by daviseford** [comment]
It also does not unset allies, and I think it should!
