### ISSUE TITLE
Common import errors

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#517]
`failedImport-Azyr-Grandfather's Blessing SPELL: Glorious Afflictions`
`failedImport-Warscroll Builder-faction:Hermdar (Lodge)`
`failedImport-Warscroll Builder-Mighty Waaagh!`
`failedImport-Warscroll Builder-Swift Strikes`

**Comment by exonian** [comment]
~failedImport-Warscroll Builder-Khorghos Khul~

**Comment by exonian** [comment]
~failedImport-Warscroll Builder-Exalted Deathbringer With Impaling Spear~
~failedImport-Warscroll Builder-Guardian of Souls With Nightmare Lantern~
