### ISSUE TITLE
Import Warscroll Builder PDF not working due to PDF changes

### ISSUE THREAD

**Issue by wspencermiller** [daviseford/aos-reminders#525]
Attaching 3 files, one is old and working,but the other two do not. It seems the logo replacement messed w/ the parser.

[List - Not Working.pdf](https://github.com/daviseford/aos-reminders/files/3697910/List.-.Not.Working.pdf)
[Old-Works.pdf](https://github.com/daviseford/aos-reminders/files/3697911/Old-Works.pdf)
[Stats - Not Working.pdf](https://github.com/daviseford/aos-reminders/files/3697912/Stats.-.Not.Working.pdf)

**Comment by daviseford** [comment]
Partially addressed by #528
