### ISSUE TITLE
Split the battlemage into different entries by realm.

### ISSUE THREAD

**Issue by Zirhark** [daviseford/aos-reminders#551]
We will need to map the importers to work for the realm source of each battlemage.

**Comment by daviseford** [comment]
> Potentially maybe make them up as seperate unit entries? Aqshy Battlemage, Hysh Battlemage etc?

**Comment by Zirhark** [comment]
So I started working down this road, but it seems to break the import when I split them up. Will need to do some digging to see if this can be resolved.
