### ISSUE TITLE
Add special rules from Core Book

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#557]
> Unless I'm missing something, it seems that reminders are not available for some of the game modes in the Core Book. For example, the special rules and command abilities for use in underground battles from the "Darkest Depths" section (pages 298-299) seem to be missing as are the command abilities for Siege Warfare battles (page 295).

From Omar D.

**Comment by JohnSchramm** [comment]
All of these modes fall under the Narrative Play section of the core rules.  I guess the question we need to ask is "Do we want this tool to support more than just Matched Play?"  

If yes, it's going to open up another can of worms with all of the available open play modes as well.  There's going to be a considerable amount of data entry and clutter while using the tool unless there is a sensible way to filter all of this out by selecting the game mode.  

If no, we can probably close this.  If we are going to spend timing filtering selections, it would probably be better served applying that treatment to the current army datasets first.

**Comment by daviseford** [comment]
I am okay with not adding these rules.
