### ISSUE TITLE
SCE "Storm Lance" WSB pdf import mixup

### ISSUE THREAD

**Issue by thundergore** [daviseford/aos-reminders#579]
Importing a WBS list containing a Drakesworn Templar unit will also add the spell 'Storm Lance' to your reminder list.

'Storm Lance' is a spell contained in the Lord-Arcanum on Celestial Dracoline scroll.

The Drakesworn Templar scroll includes the 'Stormlance' equipment option.

**Comment by daviseford** [comment]
Ooo fun
