### ISSUE TITLE
Incorrect wyldwood groves rules

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#641]
> FYI, your wyldwood groves have the wording for the cast version. The initial wood is much more limiting.

**Comment by thundergore** [comment]
I think if we go into scenery.ts for the faction and change it to:

const Scenery: TScenery = [
  {
    name: `Awakened Wyldwoods`,
    effects: [
      {
        name: `Awakened Wyldwoods`,
        desc: `After territories have been determined but before armies are set up, set up ONE Awakened Wyldwood anywhere on the battlefield more than 1" from any other terrain feature, 1" from enemy territory, and more than 6" from any objectives.`,
        when: [START_OF_SETUP],
      },
    ],
  },
]

Then we've fixed it. I would love confirmation from a Sylvaneth player before committing that though :)
