### ISSUE TITLE
Add a new flag for Mount traits

### ISSUE THREAD

**Issue by Zirhark** [daviseford/aos-reminders#655]
Add the ability to mark things as "Mount Trait: True".  If the flag is set to true then the trait should print out as a mount trait instead of a command trait if in the traits.ts.

**Comment by exonian** [comment]
For further context: At the moment, this is handled in some armies just by manually putting `(mount)` in the name of the trait https://github.com/daviseford/aos-reminders/search?q=%28mount%29&unscoped_q=%28mount%29
