### ISSUE TITLE
Error importing bone reaper pdf

### ISSUE THREAD

**Issue by Tobias1087** [daviseford/aos-reminders#673]
Tried to import the attached PDF came up with unexpected error and said to raise
[Bone%20reapers.pdf](https://github.com/daviseford/aos-reminders/files/3801514/Bone.20reapers.pdf)

**Comment by Tobias1087** [comment]
I assume this is to do with the escaped space in the name. As uploads fine when exported without

**Comment by daviseford** [comment]
Thanks for the post @Tobias1087 ! Looking into this now

**Comment by daviseford** [comment]
Fixed! Thanks again for opening this issue :)
