### ISSUE TITLE
Add feature to show Unit/Weapon profiles

### ISSUE THREAD

**Issue by simakover** [daviseford/aos-reminders#732]

**Comment by daviseford** [comment]
Hi @simakover 

This is not a planned feature for AoS Reminders. From the README.

> Will you ever add units stats or points?

> No.
> 
> This is something I will never add to AoS Reminders (unless we get a blessing from GW). It gets too close to entirely replacing the need for a battletome, and I don't want GW to think I'm trying to do that. It's a great idea but not one that I will do :)

If GW ever lends public support to this tool, we will add it. Until then, we will not :) Thanks for the comment!
