### ISSUE TITLE
Update Orruk Warclan rules

### ISSUE THREAD

**Issue by stures** [daviseford/aos-reminders#759]
I noticed that the texts on the Ironjawz and Bonesplitter rules are from the old books/warscrolls, this should be updated to the most recent ones.

**Comment by exonian** [comment]
Do you have an example or two of rules that are out of date that I could quickly check, please? (ideally from warscrolls as I can freely access those) I'm not familiar with the army, so not sure where to look. We thought we'd updated them, so definitely are keen to know what doesn't look right.

**Comment by stures** [comment]
Sure!

**Orruk Ardboys**

In the code:
```
{
        name: `Orruk-forged Shields!`,
        desc: `Roll a D6 before allocating a wound to a model with an Orruk-forged Shield. On a roll of 6 the wound is ignored.`,
        when: [WOUND_ALLOCATION],
      },
```
The Warscroll, https://www.games-workshop.com/resources/PDF/AoS_Warscrolls//aos_orruk_ardboys_eng.pdf , same as in the book

> Roll a dice each time you allocate a wound to a model carrying an Orruk-forged Shield. On a 6, that wound is negated.

**Orruk Brutes**

In the code:
```
      {
        name: `Duff Up da Big Thing`,
        desc: `Add 1 to hit rolls for an Orruk Brute if the target has a Wounds characteristic of 4+.`,
        when: [COMBAT_PHASE],
      },
```
The Warscroll https://www.games-workshop.com/resources/PDF/AoS_Warscrolls//aos_orruk_brutes_eng.pdf , same as in the book

> Add 1 to the hit rolls for attacks made by this unit that target a unit with a Wounds characteristic of 4+.

Extremely subtle changes, and the meaning is the same, but they say that they went through all the rules and tried to standardize the language as much as possible to avoid confusion.

**Comment by stures** [comment]
I never would have caught it if I did not look at the code and books side by side as reference to see if there was any special formatting that I should do when I did #590.

You can assign this to me if you want and I'll fix it while I have the stuff out and fresh in my mind!

**Comment by exonian** [comment]
That'd be fantastic, thank you!

**Comment by daviseford** [comment]
@stures was this completed or still WIP?

**Comment by stures** [comment]
I have updated the Ironjawz part in my fork, not the Savage yet, other stuff got in the way. Will try to fix it shortly!
