### ISSUE TITLE
Typo in Grave-sand Timeglass Artifact

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#774]
Artifact - Grave-sand Timeglass
Whilst the bearer is on the battlefield, once per battle, in your hero phase, you can pick an enemy HERO on the battlefield. The enemy hero suffers D3 mortal wounds. At the start of each of your subsequent hero phases, roll a D6. On a 4+ the enemy hero suffers 1 **mortal wound.ent hero phases,** on a 4+ they suffer a mortal wound.

**Comment by bszonye** [comment]
Timing on this one is weird. This initially takes effect during the hero phase (and I see that your PR moves it to `HERO_PHASE`), but it also has a followup effect in every subsequent round at `START_OF_HERO_PHASE`. Should this actually be split into two parts?

**Comment by daviseford** [comment]
See https://github.com/daviseford/aos-reminders/pull/777 for updates
