### ISSUE TITLE
Couldnt find "Slaves to darkness daemon prince" upon export from WS Buidler

### ISSUE THREAD

**Issue by RedBishop777** [daviseford/aos-reminders#810]
Hey dude thanks for all your work, the site is awesome and you could teach a few things about keeping up to date to the dudes over a battlescribe! (Pleease) Keep it up, you make this damn game actually playable!

Issue is:

![image](https://user-images.githubusercontent.com/51464822/71185233-09c3b800-2249-11ea-90c4-5270ef1557a9.png)

It seems to have a bad header for the overhauled StD Daemon Prince.

Cheers!

**Comment by daviseford** [comment]
Thanks for the report @RedBishop777  😃 

Can you click the Update button visible in your screenshot and try again? The problem _should_ be fixed. If it's not, let me know!

Thanks again 💯

**Comment by JohnSchramm** [comment]
Not sure if you want another issue opened since it's closely related but it looks like the import thinks the Daemon Prince's equipped axe selection is an artifact and endless spell.  It spuriously pulls in Wrath-axe and Volcanic-axe too.

**Comment by daviseford** [comment]
Can you post a sample PDF?

**Comment by JohnSchramm** [comment]
[test.pdf](https://github.com/daviseford/aos-reminders/files/3985333/test.pdf)

**Comment by daviseford** [comment]
@RedBishop777 @JohnSchramm , both issues are fixed
