### ISSUE TITLE
Display should be Ordered by Unit Name within phases

### ISSUE THREAD

**Issue by wspencermiller** [daviseford/aos-reminders#836]

**Comment by wspencermiller** [comment]
Looks like this is still an issue:
Correct in some:
![image](https://user-images.githubusercontent.com/2074137/71910619-dc777500-3137-11ea-8935-fba3eff75217.png)

Incorrect in others:
![image](https://user-images.githubusercontent.com/2074137/71910628-e305ec80-3137-11ea-863b-bcb4cf240e62.png)

**Comment by Flui** [comment]
Hi I would like to start contributing and this seems like a good start. So should the key `Spell` be ignored by the ordering or should `Spell: Webspinner Shaman on Archn...` be positioned before Spiker?
