### ISSUE TITLE
Order Dropdowns Alphabetically?

### ISSUE THREAD

**Issue by wspencermiller** [daviseford/aos-reminders#838]
I've heard some comments that some of the dropdowns should be ordered alphabetically. 

I think Units should be, but not sure about the others. Some are ordered that way by the TS file, but it's not explicit. Maybe this should be discussed?

**Comment by wspencermiller** [comment]
![image](https://user-images.githubusercontent.com/2074137/71910814-3bd58500-3138-11ea-8f69-23b2cd7049e7.png)

**Comment by daviseford** [comment]
Makes sense to me.
