### ISSUE TITLE
Missing Skaven Battalions

### ISSUE THREAD

**Issue by xchagger** [daviseford/aos-reminders#842]
Missing Skaven  Warpcog Convocation Engine covens. The Battalion (Warpcog Convocation) is made up of separate Engine Covens, described here:

![image](https://user-images.githubusercontent.com/7968714/71978555-88da5980-3213-11ea-8164-634b6d50504b.png)

**Comment by xchagger** [comment]
[WarscrollBuilderList (14).pdf](https://github.com/daviseford/aos-reminders/files/4035271/WarscrollBuilderList.14.pdf)


The file that was imported

**Comment by xchagger** [comment]
Error message:

![image](https://user-images.githubusercontent.com/7968714/71979317-516cac80-3215-11ea-9b06-fd9592f00a1a.png)

They did actually appear though:
![image](https://user-images.githubusercontent.com/7968714/71979352-69443080-3215-11ea-9f10-d02e6ae26ead.png)


So data is not missing, just a weird error message.

**Comment by daviseford** [comment]
Fixed! Appreciate the post :)
