### ISSUE TITLE
Skinks - Star-buckler should show on same section as Saurus - Stardrake Shields

### ISSUE THREAD

**Issue by sedulam** [daviseford/aos-reminders#874]
Just a suggestion :) The "Saurus - Stardrake Shields" ability shows up in During Shooting Phase and During Combat Phase, but the "Skinks - Star-buckler" ability which is exactly the same thing, shows up in the "During Game" phase which can make it easy to forget about it. I don't know if this is intended but I would suggest moving the skink's ability to both combat and shooting sections.

**Comment by daviseford** [comment]
will do

**Comment by sedulam** [comment]
Thanks!
