### ISSUE TITLE
Drag and drop doesn't trigger the green "Update Army" button  

### ISSUE THREAD

**Issue by sedulam** [daviseford/aos-reminders#901]
After re-ordering of actions, I don't have the option to save the modifications to the order. Although the changes are saved in the offline data, if I check the list from another device, the re-ordering will not show there.

**Comment by daviseford** [comment]
Good call out, I still haven't implemented saving the re-ordering across devices. This is next on the list!

**Comment by sedulam** [comment]
I'm really looking forward to this one. Re-ordering on the phone or tablet is very clunky. I think it would be great to be able to re-order the actions while on the computer, and just pull up the script all sorted out on mobile. 
I don't mean to be a pain, but do you see this one coming out in the near future, or is it a low priority?

**Comment by daviseford** [comment]
I will prioritize this for you :)

**Comment by sedulam** [comment]
Thank you so much! :D

**Comment by daviseford** [comment]
Working on it!

**Comment by sedulam** [comment]
I'm happy to test it out in several scenarios and types of devices if you want. Just let me know!

**Comment by daviseford** [comment]
@sedulam You may commence testing :) It's live!
