### ISSUE TITLE
Pink Horrors of Tzeentch not recognised as Horrors of Tzeentch

### ISSUE THREAD

**Issue by gannj001** [daviseford/aos-reminders#907]
[1250Tzeentch.pdf](https://github.com/daviseford/aos-reminders/files/4303148/1250Tzeentch.pdf)
While the warscroll is called "Horrors of Tzeentch", the choice in warscroll builder is "Pink Horrors of Tzeentch". Is it possible to convert Pink Horrors of Tzeentch into Horrors of Tzeentch?

**Comment by exonian** [comment]
Absolutely! There's a function specifically for name mappings like this.

Thanks for reporting it, and with the pdf attached it'll make it really easy for us to know when we've fixed it! 👍
