### ISSUE TITLE
Missing "Cold-blooded" from Seraphon Coalesced

### ISSUE THREAD

**Issue by sedulam** [daviseford/aos-reminders#920]
The allegiance ability "Cold-blooded" is not showing up.

**Comment by daviseford** [comment]
``` {
        name: `Cold-blooded`,
        desc: `Ignore modifiers (positive or negative) to the Bravery characteristic of COALESCED units.`,
        when: [BATTLESHOCK_PHASE],
      },```

Do you not see it under Battleshock?

**Comment by sedulam** [comment]
I know what happened. I imported [this list](https://drive.google.com/open?id=1nHoe7sRb-ma_bU9uvzaPzCE8aRmRx08g), but only "Koatl's Claw" was selected, leaving out "Coalesced". A list can be both of these constellations at the same time. Pretty much like "Starborne + Fangs of Sotek".
I didn't understand the mechanism at the time. Do you think the adding of the constellation can be automated?

**Comment by daviseford** [comment]
I will check it out

**Comment by sedulam** [comment]
An idea would be, if the list is either "Draconthion's Tail" or "Fangs of Sotek", then it's mandatory to be Starborne. If it is "Koatl's Claw" or "Thunder Lizard" it must be Coalesced.
