### ISSUE TITLE
Mix Seraphon items

### ISSUE THREAD

**Issue by twbillings** [daviseford/aos-reminders#933]
I couldn't complete my Fangs of Sotek list because I couldn't find Ixtli Grubs, Serpent God Dagger, and Tide of Serpents.  I just started AoS about 3 months ago and I have found AoS Reminders to be awesome.  I actually just became a premium member.

**Comment by daviseford** [comment]
Thanks, I will look into these!

Thanks for subscribing ❤️

**Comment by twbillings** [comment]
I just got into AoS and AoS reminders is a god send.  Subscribing was the least I could do!  My 11 year old, and myself of course, are able to play at a good level because of your work.  Thank you for all you do.  
    On Friday, April 24, 2020, 07:41:59 PM CDT, Davis Ford <notifications@github.com> wrote:  
 
 


Thanks, I will look into these!

Thanks for subscribing ❤️

**Comment by daviseford** [comment]
> Serpent God Dagger

When you select the Fangs of Sotek Constellation, this artifact is added to your army's composition automatically.

> Ixtli Grubs

We have this written as `Itxi Grubs`. Do we have a typo? 🤔 Regardless, it should be under artifacts

> Tide of Serpents

This should be found under the Spells section.
