### ISSUE TITLE
Cities of Sigmar: Incorrect faction ability

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#951]
> Hello, just trying this site for the first time, good work!

> When selecting Cities of Sigmar faction Tempest's Eye it shows that the army also gets Rapid Redeploy as a faction command ability, when they should have none! This ability is only supposed to be in the Hallowheart army.

> Thank you

**Comment by exonian** [comment]
According to my battletome, Rapid Redeploy is Tempest's Eye.

I think we have this correct already. I also checked the other allegiance abilities of each of the two in case the report just had the wrong name but the right idea, but I couldn't find any discrepancies.
