### ISSUE TITLE
Endless Spell: Bound Ravenak's Gnashing Jaws - Empowered by Ghur (Ghur)

### ISSUE THREAD

**Issue by sedulam** [daviseford/aos-reminders#953]
The bound version of this endless spell doesn't have "Empowered by Ghur (Ghur)", but it shows it AoS Reminders.

**Comment by sedulam** [comment]
Same thing for "Endless Spell: Bound Emerald Lifeswarm - Empowered by Ghyran (Ghyran)"
The bound version is not empowered by Ghyran.

**Comment by exonian** [comment]
Nice catch, thanks. Working on it now.
