### ISSUE TITLE
Flesh eater Courts missing unit

### ISSUE THREAD

**Issue by yllomot** [daviseford/aos-reminders#955]
I was looking to add the Vampire Lord on Zombie Dragon, but it's not listed as an option. The only available option is Royal Zombie Dragon.

**Comment by exonian** [comment]
Unlike the Royal Zombie Dragon and Abhorrant Ghoul King on Royal Zombie Dragon, the VLoZD is available from Legions of Nagash (and so in the Grand Host, Legion of Night, Legion of Sacrament and Legion of Blood allegiances), rather than FEC. So I'm not sure it should be there, tbh

**Comment by yllomot** [comment]
It's just that it's in the FEC battletome, so I figured it was part of the FEC.

**Comment by exonian** [comment]
It is? I thought it was just Royal Zombie Dragon and Abhorrant Ghoul King on Royal Zombie Dragon, both of which we have. I don't actually have the battletome to hand, but I can't find any indication of it being in FEC (eg on warscrollbuilder). Do you have a pic or anything from your battletome?

**Comment by exonian** [comment]
@daviseford I think this ticket should probably be closed.

@yllomot happy to try to work out this misunderstanding, but as it stands I'm quite confident that that unit shouldn't be in the FEC list
