### ISSUE TITLE
Sorting does not have effect on exported PDF

### ISSUE THREAD

**Issue by sedulam** [daviseford/aos-reminders#956]
While re-ordering the reminders, the order by which they appear in the PDF is the default one. It makes sense for the order in the site, to be the order that gets printed on the PDF.

**Comment by sedulam** [comment]
Same thing for "Play" mode. The re-ordering in the "Edit" mode, does not get persisted in the "Play" mode.

**Comment by exonian** [comment]
What browser are you using?
I tried to replicate (Chrome on windows) and both PDF and play mode seemed to be doing as expected, so wonder if it's a browser issue. Or are you testing across two devices, with saving and loading?

**Comment by sedulam** [comment]
I'm using Chrome, but just on a single device. I'll try with Edge and let you know.

**Comment by sedulam** [comment]
I have tried with Edge and Firefox, and I have the same results. Re-ordering does not take effect on the Play mode or the PDF. Let me know if I can provide more info.
I can also make a screen capture video to show if you want.

**Comment by exonian** [comment]
If you could make a video or gif, that'd be grand. I'll try to make one of what I'm seeing too, in case I've misunderstood the intended behaviour

**Comment by exonian** [comment]
![aosr-ordering-play](https://user-images.githubusercontent.com/1237986/85295380-b9e3d900-b497-11ea-84ca-3fd6c7c04608.gif)

**Comment by daviseford** [comment]
@sedulam could you please do a screen recording?

**Comment by sedulam** [comment]
Sorry for the delay, my laptop broke at the beginning of the week. Which is kinda useful because this  is a new computer, so it removes any debugging issues which would be related to something very local to the other one (I guess :)).
Anyway, I figured out that the re-ordering works in some sections, but not in others. For instance, in this recording, notice how moving the "Itxi Grubs" in the "Start of Hero Phase" works, but the same does not happen for "During Hero Phase". Recording: https://drive.google.com/file/d/1A5X8ML3OPw3bKfH8ELYMVKDVwZ4sH5qj/view?usp=sharing
I hope this helps.

Please let me know as soon as I can take the video offline. I don't have anything special there, but I was lazy to do further editing :)

**Comment by exonian** [comment]
Thanks. I've requested access as that file appears to be private.
Sounds like there's something odd going on, so very interested now :)

**Comment by sedulam** [comment]
@exonian I thought I had set permissions properly, but G Drive permissions have had issues in the past. Anyway, it's shared now, LMK if you still have issues.

**Comment by exonian** [comment]
Thanks again
From the dark mode video, I'm assuming you're a subscriber? If so, would you be able to generate a Share Link and paste that here, please? It looks like it's going to be a bit involved, so having the exact same list to work on should make it easier to replicate and then isolate.

**Comment by sedulam** [comment]
Here you go: https://aosreminders.com/?army=1qNKKOp3K

**Comment by exonian** [comment]
Hero, thanks

So I've had a quick play and can reproduce. I then removed the Slann and the Itxi Grubs started being orderable properly. Added the Slann back and it broke the Grubs...

Not 100% what to conclude from this but it's definitely interesting. I might do #958 and see if that has any effect, as it's an unusual situation and there's circumstantial evidence against it 😁

**Comment by daviseford** [comment]
Thank you very much @sedulam . I'll try to look into this over the weekend. I really appreciate your attention to detail and thorough bug reports :)

You are responsible for a lot of improvements to AoS Reminders, so thank you for your continued support!

--

@exonian, I'll message you on Discord before I start working on it, and if I discover anything interesting. Of course, if you beat me to it, that's awesome too :)

**Comment by sedulam** [comment]
You created something amazing, I'm more than happy to help!

PS: you should do a rap for AoSReminders like the one you shared on Twitter :D That was awesome
