### ISSUE TITLE
Missing CoS Battlemage spells

### ISSUE THREAD

**Issue by Holger487** [daviseford/aos-reminders#978]
**Missing is Battlemage (Chamon)**
Transmutation of Lead has a casting value of 7. 
If successfully cast, pick 1 enemy unit within 18" of the caster that is visible to them.
Until your next hero phase, halve the Move characteristic of the unit you picked, rounding up. 
In addition, if that unit has a Save characteristic of 2+, 3+ or 4+, you can
re-roll hit rolls of 1 for attacks that target that unit until your next hero phase.

**Missing is Battlemage (Hysh)**
Pha’s Protection has a casting value of 5.
If successfully cast, pick 1 friendly unit within 18" of the caster that is visible to them. 
Subtract 1 from hit rolls for attacks that target that unit until your next hero phase.

**Missing is Battlemage (Shyish)**
Pall of Doom has a casting value of 6.
If successfully cast, pick 1 enemy unit within 18" of the caster that is visible to them.
Subtract 2 from the Bravery characteristic of that unit until your next hero phase.

**Missing is Battlemage (Ulgu)**
Mystifying Miasma has a casting value of 4.
If successfully cast, pick 1 enemy unit within 18" of the caster that is visible to them.
That unit cannot run until your next hero phase. In addition, subtract 2 from
charge rolls for that unit until your next hero phase.

**Comment by wspencermiller** [comment]
Thanks, @Holger487!

I just checked and added all battlemages to the Prod version and see this:
![image](https://user-images.githubusercontent.com/2074137/88100383-16531a80-cb62-11ea-8760-56adc53d4874.png)

When you add a battlemage it's specific to that realm, so it only has access to that realm spell. Are you seeing/experiencing something different? 

If so, could you take a screenshot that includes the following:

- Units
- Spells
- During Hero Phase section

Thanks!

**Comment by Holger487** [comment]
![image](https://user-images.githubusercontent.com/68614555/88100978-a4002b80-cb9d-11ea-932f-4ee910a3f3e5.png)

**Comment by Holger487** [comment]
picking battlemage only brings up half, and cant get em to show even if i pick the realm mages directly

**Comment by exonian** [comment]
@wspencermiller What's your version number (in the footer)? I think I'm seeing the same as @Holger487, on v3.1.0

**Comment by Holger487** [comment]
yeah its 3.1.0

**Comment by exonian** [comment]
Think it might have been some overzealous find-and-replace in this tbh 😅 https://github.com/daviseford/aos-reminders/commit/0328627943017e94c56e66b56c054a28d3f54b75

**Comment by wspencermiller** [comment]
I found the issue. 

There are realm specific battlemages in the unit selection, but also a generic battlemage. When picking the generic battlemage, it needs to get all of the realm spells. This is so it can support the Azyr importing and 

Bug: When selecting "Battlemage" (without a realm) it only populates certain spells, but should populate all Battlemage Realm spells. 

Bug: When importing "Battlemages" from Warscroll Builder it only populates some of the spells for the battlemages, not all. 


I used Warscroll builder to build a list with 6 battlemages. It imported the units, but did not import the spells:
![image](https://user-images.githubusercontent.com/2074137/88101819-2ff56180-cb64-11ea-82b6-c70c4ff74908.png)
Here's the PDF:
[testingBattlemages.pdf](https://github.com/daviseford/aos-reminders/files/4955926/testingBattlemages.pdf)

**Comment by Holger487** [comment]
8 realms and only half works for me, even if i pick the specific battlemages (with realms)

**Comment by wspencermiller** [comment]
@exonian 
![image](https://user-images.githubusercontent.com/2074137/88102062-91b5cb80-cb64-11ea-8a6e-c117075ac1d7.png)

Found it ;)

**Comment by exonian** [comment]
@daviseford This is fixed
