### ISSUE TITLE
Awakened wyldwoods placement rule

### ISSUE THREAD

**Issue by blair-cmd** [daviseford/aos-reminders#986]
I think the awakened wyldwoods placement rule is just being taken from the battle tome and not pulling down the errata from the 2019 core book. Meaning it has to be more than 3" from any other terrain features.

**Comment by exonian** [comment]
Related: https://github.com/daviseford/aos-reminders/issues/641
ie we _thought_ we'd fixed it... :D

**Comment by exonian** [comment]
Oh no, my mistake. I think this is a separate issue.
@blair-cmd Do you have the FAQ wording to hand?
